### ISSUE TITLE
Lack information of atomic type in training dataset file: `Training_Cao_20220823.cfg`

### ISSUE THREAD

**Issue by ZLI-afk** [yifan-henry-cao/MachineLearningPotential#1]
As described in the title, could you please clearify the atom type map in the `Training_Cao_20220823.cfg` file? Many thanks

**Comment by yifan-henry-cao** [comment]
Hello!

Thanks for pointing out! I have updated the README file, the atom type mapping for the potential and training dataset are: {0: 'Cr', 1: 'Co', 2: 'Ni'}.

I also updated an training_example.sh shell code for training the MTP potential using the dataset!
